# Generated by Django 5.2.17 on 2026-09-20 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('song', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('inspired', 'Inspired a post')], default='new', max_length=12)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=100, unique=True)),
                ('permalink', models.URLField()),
                ('caption', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-published_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='IdeaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.idea')),
            ],
        ),
    ]
