# Generated by Django 5.2.17 on 2026-09-20 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ['name', 'email'],
            },
        ),
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['sender__name', 'sender__email', '-created_at']},
        ),
        migrations.AddField(
            model_name='idea',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ideas', to='core.sender'),
        ),
    ]
